### ISSUE TITLE
Invalid syntax error..

### ISSUE THREAD

**Issue by sirvon** [billyshambrook/aiofirebase#3]
I keep getting this...

``` python
  File "firebaseaioXNA.py", line 6
    await firebase.get(path='dinosaurs')
                 ^
SyntaxError: invalid syntax
```

**Comment by sirvon** [comment]
``` python
await
```

"...you can't use this outside of another coroutine, otherwise you'll get a syntax error."

taken from [link](http://stackabuse.com/python-async-await-tutorial/)

**Comment by billyshambrook** [comment]
Hey @sirvon, thanks for raising the issue. That is correct, you will need to run this within a async function.

``` python
import asyncio

import aiofirebase

firebase = aiofirebase.FirebaseHTTP("https://<YOUR-FIREBASE-APP>.firebaseio.com/")

async def get_dinosaurs():
    await firebase.get(path='dinosaurs')

loop = asyncio.get_event_loop()
loop.run_until_complete(get_dinosaurs())
```

I will look at how to document each step in a better way. Thanks

**Comment by billyshambrook** [comment]
The confusion seems to be with how I have documented the examples. Will close this and cover the fix to the documentation in #4. Thanks

**Comment by sirvon** [comment]
when i run this code....

``` python
import asyncio
import aiofirebase

firebase = aiofirebase.FirebaseHTTP("https://xxxxx.firebaseio.com/")

async def get_dinosaurs():
    await firebase.get(path='dinosaurs')

    loop = asyncio.get_event_loop()
    loop.run_until_complete(get_dinosaurs())
```

in firebase i have...

``` json
{"dinosaurs": "ok"}
```

and i get this output in terminal...

``` bash
$ python3 firebaseaio.py
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10b4bbe48>

```

aren't I supposed to get

``` bash
 "ok"
```

**Comment by billyshambrook** [comment]
The output is saying that the loop wasn't closed, you can fix that by adding `loop.close()` after the `run_until_complete` call (though the loop is garbage collected by Python)

Can try replacing `await firebase.get(path='dinosaurs')` with...  

``` python
result = await firebase.get(path='dinosaurs')
print(result)
```

That should print the result of that call.

**Comment by sirvon** [comment]
https://loqoonyc.firebaseio.com/dinosaurs
still nothing

**Comment by billyshambrook** [comment]
Hey @sirvon,

I am unable to re-produce the issue since the last release. Earlier this week I made a new release (0.2.0) after fixing your other raised issue, have you updated (check using `pip freeze`)? 

Below are two examples that I have tested with your URL.

``` python
import asyncio
import aiofirebase

firebase = aiofirebase.FirebaseHTTP("https://loqoonyc.firebaseio.com")

async def get_dinosaurs():
    result = await firebase.get(path='dinosaurs')
    print(result)

loop = asyncio.get_event_loop()
loop.run_until_complete(get_dinosaurs())
loop.run_until_complete(firebase.close())
loop.close()
```

Or if you put dinosaurs in the URL given to the `FirebaseHTTP` class, you can call get without any arguments...

``` python
import asyncio
import aiofirebase

firebase = aiofirebase.FirebaseHTTP("https://loqoonyc.firebaseio.com/dinosaurs")

async def get_dinosaurs():
    result = await firebase.get()
    print(result)

loop = asyncio.get_event_loop()
loop.run_until_complete(get_dinosaurs())
loop.run_until_complete(firebase.close())
loop.close()
```

You should see `ok` printed in the terminal.

Thanks

**Comment by sirvon** [comment]
It works!
That was exactly it...hadn't installed the new release.

Thanks for your time and lib!
